config/routes.rb
FitnessManager::Application.routes.draw do

  devise_for :coaches, controllers: {
    registrations: 'coaches/registrations'
  }
  devise_for :clients, controllers: {
    registrations: 'clients/registrations'
  }

  resources :coach_steps

  resources :messages do
    collection do
      post :inbound
      get :inbound
    end
    member do
      post :confirm
      get :reply
    end
  end

  resources :coaches, shallow: true do

    collection do
      get :settings
      get :edit_profile
      put :update_profile
    end

    resources :messages do
      collection do
        post :inbound
        get :inbound
        get :scheduled
      end
      member do
        post :confirm
      end
    end

    resources :clients do
      collection do
        get :checkins
      end
      resources :messages
      member do
        get :info
        get :goals
        get :dashboard
        put :active
        put :deactive
      end
      resources :habits do
        member do
          put :active
          put :deactive
        end
      end
      resources :goals do
        member do
          put :active
          put :deactive
        end
      end
    end

    resources :groups do
      resources :messages
      member do
        get :info
        put :active
        put :deactive
      end
    end
  end

  root :to => "pages#index"
  match '/about' => 'pages#about'
  match '/tips' => 'pages#tips'
  
end

app/models/coach.rb
class Coach < ActiveRecord::Base
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessible :email,
    :password,
    :password_confirmation,
    :remember_me,
    :first_name,
    :surname,
    :brand_name,
    :clients_attributes,
    :groups_attributes,
    :brand_name,
    :phone_number

  state_machine :state, :initial => :inactive do
    event :activate do
      transition all => :active
    end

    event :deactivate do
      transition all => :inactive
    end
  end

  has_many :clients
  accepts_nested_attributes_for :clients, :reject_if => :all_blank
  has_many :checkins, through: :clients

  has_many :groups
  accepts_nested_attributes_for :groups, :reject_if => :all_blank

  has_many :sent_messages, as: :sender, class_name: "Message", dependent: :destroy
  has_many :messages, as: :receiver, dependent: :destroy

  validates :phone_number, :length => { :maximum => 10}, presence: true
  validates :first_name, :surname, :brand_name, :email, presence: true
  validates_format_of :phone_number,
    :message => "telephone number must contains only digits and plus sign.",
    :with => /^[+0-9]+$/,
    :if => :active?

  def name
    "#{first_name} #{surname}"
  end

  def to_param
    "#{id}-#{first_name.downcase}-#{surname.downcase}"
  end

  def past_messages
    Message.where("send_at <= ?", Time.zone.now).
      where("(sender_id = #{id} AND sender_type = 'Coach') OR (sender_type = 'Client' AND receiver_id = #{id})").
      where(state: "confirmed").
      order("send_at DESC")

      #page(params[:page])
  end

  def scheduled_messages
    self.sent_messages.
      where("NOT (send_at <= ? AND state = 'confirmed')", Time.zone.now).
      order("send_at DESC")

      #page(params[:page])
  end
end

app/models/message.rb
class Message < ActiveRecord::Base
  attr_accessible :client_id,
    :coach_id,
    :content,
    :title,
    :delayed_job_id,
    :send_at,
    :send_at_date,
    :send_at_time,
    :sender
    :state

  before_save :confirm_if_past
  before_validation :set_datetimes # convert accessors back to db format
  validates :content, presence: true

  belongs_to :sender, polymorphic: true
  belongs_to :receiver, polymorphic: true

  before_destroy :destroy_delayed_jobs

  attr_accessor :send_at_date, :send_at_time

  after_initialize :get_datetimes # convert db format to accessors
  after_create :confirm_and_send_mail

  def confirm_if_past
    if self.send_at <= Time.now
      self.state = :confirmed
    end
  end

  def confirm_and_send_mail
    if self.send_at <= Time.now
      self.state = "confirmed"
      if self.receiver.is_a?(Client) || self.receiver.is_a?(Coach)
        self.send_mail
      elsif self.receiver.is_a?(Group)
        self.receiver.broadcast_to_clients(self)
      end
    end
  end

  def get_datetimes
    t = Time.now
    self.send_at ||= t-t.sec-t.min%15*60  # if the send_at time is not set, set it to now (rounded down to 0, 15, 30, 45 mins to match the timepicker)

    self.send_at_date ||= self.send_at.strftime("%Y-%m-%d")
    self.send_at_time ||= self.send_at.strftime("%I:%M %p")
  end

  def set_datetimes
    self.send_at = "#{self.send_at_date} #{self.send_at_time}:00" # convert the two fields back to db
  end

  def send_mail
    job = ClientMailer.delay(run_at: self.send_at).new_message(self)
    self.update_attributes(delayed_job_id: job.id)
  end

  # def self.send_to_coach message_hash, sender
  #   message = sender.coach.messages.new message_hash
  #   message.message_type = 1
  #   message.sender = sender
  #   message.save
  # end


  state_machine :state, :initial => :unconfirmed do
    after_transition :on => :confirm, :do => :send_mail

    event :confirm do
      transition :unconfirmed => :confirmed
    end

    event :unconfirm do
      transition :confirmed => :unconfirmed
    end

    event :send do
      transition :confirmed => :sent
    end
  end

  def self.send_to_clients message_hash, client_ids, sender
    client_ids.each do |cid|
      client = sender.clients.find cid
      m = client.messages.new message_hash
      m.sender = sender
      m.save
    end if client_ids.present?
  end

  def self.send_to_groups message_hash, group_ids, sender
    group_ids.each do |gid|
      group = sender.groups.find gid
      m = group.messages.new message_hash
      m.sender = sender
      m.save
    end if group_ids.present?
  end



  private

  def destroy_delayed_jobs
    Delayed::Job.destroy_all(id: self.delayed_job_id) if self.delayed_job_id
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  BODY_SPLIT = ":: Reply above this line ::"
  before_filter :load_messagable, only: [:index, :new, :scheduled]

  def index
    # if messagable is available, it's viewing that messagable's messages
    # if not, it's creating message for multiple clients and groups,
    # or sending message to his coach if client logged in instead of coach
    redirect_to root_path unless coach_signed_in? || client_signed_in?

    # past_messages = all messages in the past AND confirmed
    # scheduled_messages = everything else (NOT (past AND confirmed))

    if mobile?
      if coach_signed_in?
        render "messages/index"
      else
        render "clients/messages"
      end
    end
  end

  def reply
    @message = Message.find params[:id]
  end

  def scheduled
    
  end

  def new
    if mobile?
      if @messagable.present?
        logger.debug("A")
        logger.debug(@messagable.inspect)
        render
      else
        logger.debug("B")
        render "new_batch_messages"
      end
    else
      if @messagable.present?
        logger.debug("A")
        logger.debug(@messagable.inspect)
        render layout: false
      else
        logger.debug("B")
        render "new_batch_messages", layout: false
      end
    end
  end

  def edit
    @message = Message.find params[:id]
    if mobile?
      render
    else
      render layout: false
    end
  end

  def create
    if coach_signed_in?
      if params[:client_ids] || params[:group_ids]
        Message.send_to_clients params[:message], params[:client_ids], current_coach
        Message.send_to_groups params[:message], params[:group_ids], current_coach
        redirect_to :back, notice: "Top Trainer successfully created your message."
      else
        receiver = current_coach.clients.where(id: params[:client_id]).first || current_coach.groups.where(id: params[:group_id]).first
        unless receiver.present?
          redirect_to :back, alert: "Top Trainer failed to create your message."
          return
        end
        message = receiver.messages.new params[:message]
        message.sender = current_coach

        if message.save
          redirect_to :back, notice: "Top Trainer successfully created your message."
        else
          redirect_to :back, alert: "Top Trainer failed to create your message."
        end
      end
    elsif client_signed_in?
      coach = Coach.find_by_id current_client.coach.id
      message = coach.messages.new params[:message]
      message.state = :confirmed
      message.sender = current_client
      message.message_type = 1 if mobile?
      if message.save
        redirect_to :back, notice: "Top Trainer successfully created your message."
      else
        redirect_to :back, alert: "Top Trainer failed to create your message."
      end
    else
      redirect_to root_path, alert: "Login please"
    end
  end

  def update
    @message = Message.find(params[:id])

    if (@message.sender == current_coach || @message.sender == current_client) && @message.update_attributes(params[:message])
      redirect_to :back, notice: 'This message was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @message = Message.find(params[:id])
    receiver = @message.receiver

    if coach_signed_in? && ( @message.sender == current_coach || @message.receiver == current_coach )
      @message.destroy
    elsif client_signed_in? && ( @message.sender == current_client || @message.receiver == current_client)
      @message.destroy
    end

    respond_to do |format|
      format.html { redirect_to receiver }
      format.js
    end
  end

  def inbound
    event = JSON.parse(params[:mandrill_events])[0]
    recipient_email = event['msg']['to'][0][0]
    sender_email = event['msg']['from_email']

    recipient_email.match(/C(\d+)-MB@/)
    email_body = MessagesController.clean_body(event['msg']['text'])
    if $1.present?
      client = Client.find $1

      coach = Coach.find_by_email(sender_email)
      if coach.present? && coach.clients.includes?(client)
        client.messages.create(content: email_body, sender: coach)
      elsif client.email == sender_email
        client.coach.messages.create(content: email_body, sender: client)
      end
    end

    render nothing: true
  end

  def confirm
    @message = Message.find(params[:id])
    if @message.confirmed?
      @message.unconfirm
    else
      @message.confirm
    end
    respond_to do |format|
      if mobile?
        format.html { redirect_to scheduled_coach_messages_path(current_coach),
          notice: 'This piece of message was successfully confirmed.'}
        format.js
      else
        format.html { redirect_to :back,
          notice: 'This piece of message was successfully confirmed.'}
        format.js
      end
    end
  end

  private

  def self.clean_body(body)
    new_body_end = body.to_s.index(BODY_SPLIT) || body.to_s.length
    body = body.to_s[0, new_body_end].strip

    lines = body.to_s.split("\n")
    while lines.any?
      line = lines.last.strip

      if line.blank? or line.match(/^[<>]+$/) or line.match(/.* wrote:/)
        lines.pop
      else
        break
      end
    end

    return lines.join("\n")
  end

  # alternative option:
  def load_messagable
    klass = [Client, Coach, Group].detect { |c| params["#{c.name.underscore}_id"] }
    if klass.present?
      @messagable = klass.find(params["#{klass.name.underscore}_id"])
    end
  end
end

app/views/messages/_message.html.erb
<div class="message_box <%= message.sender.class.name.downcase %>">
  <div>
    <%= link_to message, method: :delete, confirm: "Sure?", class: "btn btn-mini pull-right" do %>
      <i class="icon-remove"></i>
    <% end if coach_signed_in? %>
    <p>
      <%= format_message_detail(message) %>
    </p>
  </div>
  <small>
    <%= format_message_info(message) %>
  </small>
</div>

app/views/messages/_scheduled_messages.html.erb
<table class="table table-bordered table-stripped">
  <thead>
    <tr>
      <th>To:</th>
      <th>Scheduled Message</th>
      <th>Time</th>
      <th>Confirmed?</th>
      <th>Action</th>
      <th>Trash</th>
    </tr>
  </thead>

  <tbody>
    <% messages.each do |message| %>
      <tr id="msg-<%= message.id %>">
        <td>
          <%= link_to(message.receiver.name, message.receiver) %>
        </td>
        <td>
          <%= link_to message.content, edit_message_path(message), data: { target: "#myModal", toggle: "modal" } %>
        </td>
        <td>
          <%= l message.send_at %>
        </td>
        <td>
          <% if message.confirmed? %>
            <span class="label label-success">Confirmed</span>
          <% else %>
            <span class="label label-important">Unconfirmed</span>
          <% end %>
        </td>
        <td>
          <% if message.confirmed? %>
            <button type="button" class="btn btn-mini btn-success disabled" disabled="disabled">Confirmed</button>
          <% else %>
            <%= button_to "Confirm", confirm_message_path(message), class: "btn btn-mini btn-warning", remote: true %>
          <% end %>
        </td>
        <td>
          <%= link_to message_path(message), class: "btn btn-mini", method: :delete, confirm: "Sure?", remote: true do %>
            <i class="icon-trash"></i>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/messages/confirm.js.erb
<% if @message.confirmed? %>
  $("tr#msg-<%= @message.id %> form.button_to input").val("Unconfirm");
  $("tr#msg-<%= @message.id %> form.button_to input").removeClass("btn-success");
  $("tr#msg-<%= @message.id %> form.button_to input").addClass("btn-danger");

  $("tr#msg-<%= @message.id %> span.label").html("Confirmed");
  $("tr#msg-<%= @message.id %> span.label").removeClass("label-important");
  $("tr#msg-<%= @message.id %> span.label").addClass("label-success");
<% else %>
  $("tr#msg-<%= @message.id %> form.button_to input").val("Confirm");
  $("tr#msg-<%= @message.id %> form.button_to input").removeClass("btn-danger");
  $("tr#msg-<%= @message.id %> form.button_to input").addClass("btn-success");

  $("tr#msg-<%= @message.id %> span.label").html("Unconfirmed");
  $("tr#msg-<%= @message.id %> span.label").removeClass("label-success");
  $("tr#msg-<%= @message.id %> span.label").addClass("label-important");
<% end %>

app/views/messages/destroy.js.erb
$("#msg-<%= @message.id %>").fadeOut();

app/views/messages/edit.html.erb
<%= simple_form_for @message, html: { class: "form-horizontal" } do |f| %>
  <%= f.error_notification %>
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Edit Message</h3>
  </div>

  <div class="modal-body">
    <%= f.input :title, label: 'Subject/ Title:' %>
    <%= f.input :content, placeholder: "Your message...", input_html: { cols: 10, rows: 8 } %>

    <div class="control-group">
      <%= f.label :send_at, label: "To be sent at:" %>
      <div class="controls">
        <%= f.text_field :send_at_date, class: "input-small", 'data-behaviour' => 'datepicker-message' %>
        <%= f.text_field :send_at_time, class: "input-small", 'data-behaviour' => 'timepicker' %>
      </div>
    </div>
  </div>

  <div class="modal-footer">
    <%= f.button :submit, "Edit", class: "btn btn-primary" %>
    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
  </div>
<% end %>

app/views/messages/index.html.erb
<% if coach_signed_in? %>
  <%= render 'coaches/nav' %>
<% else %>
  <%= render 'clients/nav' %>
<% end %>
<section>
  <h1>
    <% if coach_signed_in? %>
      <%= link_to raw('<i class="icon-envelope"></i> New Message'), new_message_path, data: { target: "#myModal", toggle: "modal" }, class: "btn pull-right" %>
    <% else %>
    <%= link_to raw('<i class="icon-envelope"></i> New Message'), new_client_message_path, data: { target: "#myModal", toggle: "modal" }, class: "btn pull-right" %>
    <% end %>
    Message Dashboard
  </h1>

  <hr />

  <div class="row-fluid">
    <% if coach_signed_in? %>
      <div class="span12">
        <h3>
          Scheduled Messages
        </h3>
        <table class="table table-bordered">
          <thead>
            <tr>
              <th>To:</th>
              <th>Scheduled Message</th>
              <th>Time</th>
              <th>Confirmed?</th>
              <th>Action</th>
              <th>Trash</th>
            </tr>
          </thead>
          <tbody>
            <% @messagable.scheduled_messages.each do |message| %>
              <tr id="msg-<%= message.id %>">
                <td>
                  <%= link_to message.receiver.name, message.receiver %>
                </td>
                <td>
                  <%= link_to message.title, edit_message_path(message), data: { target: "#myModal", toggle: "modal" } %>
                </td>
                <td>
                  <%= l message.send_at %>
                </td>
                <td>
                  <% if message.confirmed? %>
                    <span class="label label-success">Confirmed</span>
                  <% else %>
                    <span class="label label-important">Unconfirmed</span>
                  <% end %>
                </td>
                <td>
                  <% if message.confirmed? %>
                    <%= button_to "Unconfirm", confirm_message_path(message), :class => "btn btn-mini btn-danger", remote: true %>
                  <% else %>
                    <%= button_to "Confirm", confirm_message_path(message), :class => "btn btn-mini btn-success", remote: true %>
                  <% end %>
                </td>
                <td>
                  <%= link_to message_path(message), :class => "btn btn-mini", :method => :delete, :confirm => "Sure?", :remote => true do %>
                    <i class="icon-trash"></i>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% end %>

      <% if coach_signed_in? %>
      <h3>
        Recent Messages History
      </h3>
      <% end %>
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>To</th>
            <th>From</th>
            <th>Past Message</th>
          </tr>
        </thead>
        <tbody>
          <% @messagable.past_messages.each do |message| %>
          <% if message.sender.is_a?(Client) %>
            <tr class="marksender">
          <% else %>
            <tr>
          <% end %>
              <td>
                <%= link_to message.receiver.name, message.receiver %>
              </td>
              <td>
                <% if message.sender.is_a?(Client) %>
                  <%= link_to message.sender.name, client_path(message.sender) %>
                <% else %>
                  <%= message.sender.name %>
                <% end %>
              </td>
              <td>
                <%= message.title %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</section>

app/views/messages/new.html.erb
<%= simple_form_for [@messagable, @messagable.messages.new], html: { name: "new_message", class: "form-horizontal" } do |f| %>
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">New Message for <%= @messagable.name %></h3>
  </div>

  <div class="modal-body">
    <%= f.input :title, label: 'Subject/ Title:' %>

    <% if coach_signed_in? %>
      <div class="control-group">
        <%= f.label :send_at %>
        <div class="controls">
          <%= f.text_field :send_at_date, class: "input-small", 'data-behaviour' => 'datepicker-message' %>
          <%= f.text_field :send_at_time, class: "input-small", 'data-behaviour' => 'timepicker', 'data-mindate' => f.object.send_at_date, 'data-mintime' => f.object.send_at.to_i  %>
        </div>
      </div>
    <% end %>

    <%= f.input :content, placeholder: "Your message...", input_html: { cols: 10, rows: 8, required: true } %>
  </div>

  <div class="modal-footer">
    <%= f.button :submit, "Send", disable_with: "Sending", class: "btn btn-primary" %>
    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
  </div>
<% end %>

app/views/messages/new_batch_messages.html.erb
<%= simple_form_for Message.new, html: { name: "new_message", class: "form-horizontal" } do |f| %>
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">New Message</h3>
  </div>

  <div class="modal-body">
    <%= f.input :title, label: 'Subject/ Title:' %>

    <div class="control-group">
      <%= label_tag "Send to", nil, class: "control-label" %>
      <div class="controls">
        <%= select_tag :client_ids, options_from_collection_for_select(current_coach.clients, :id, :name), style: "width:100px;", multiple: true, class: 'select2-select' %>
        <%= select_tag :group_ids, options_from_collection_for_select(current_coach.groups, :id, :name), style: "width:100px;", multiple: true, class: 'select2-select' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :send_at %>
      <div class="controls">
        <%= f.text_field :send_at_date, class: "input-small", 'data-behaviour' => 'datepicker-message' %>
        <%= f.text_field :send_at_time, class: "input-small", 'data-behaviour' => 'timepicker' %>
      </div>
    </div>

    <%= f.input :content, placeholder: "Your message...", input_html: { cols: 10, rows: 8, required: true } %>

  </div>

  <div class="modal-footer">
    <%= f.button :submit, "Send", disable_with: "Sending", class: "btn btn-primary" %>
    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
  </div>
<% end %>