config/routes.rb
FitnessManager::Application.routes.draw do

  devise_for :coaches, controllers: {
    registrations: 'coaches/registrations'
  }
  devise_for :clients, controllers: {
    registrations: 'clients/registrations'
  }

  resources :coach_steps

  resources :messages do
    collection do
      post :inbound
      get :inbound
    end
    member do
      post :confirm
      get :reply
    end
  end

  resources :coaches, shallow: true do

    collection do
      get :settings
      get :edit_profile
      put :update_profile
    end

    resources :messages do
      collection do
        post :inbound
        get :inbound
        get :scheduled
      end
      member do
        post :confirm
      end
    end

    resources :clients do
      collection do
        get :checkins
      end
      resources :messages
      member do
        get :info
        get :goals
        get :dashboard
        put :active
        put :deactive
      end
      resources :habits do
        member do
          put :active
          put :deactive
        end
      end
      resources :goals do
        member do
          put :active
          put :deactive
        end
      end
    end

    resources :groups do
      resources :messages
      member do
        get :info
        put :active
        put :deactive
      end
    end
  end

  root :to => "pages#index"
  match '/about' => 'pages#about'
  match '/tips' => 'pages#tips'
  
end

app/models/group.rb
class Group < ActiveRecord::Base
  attr_accessible :name, :note, :client_ids, :state
  validates :name, presence: true

  belongs_to :coach
  has_many :messages, as: :receiver, dependent: :destroy

  has_and_belongs_to_many :clients,
    :after_add => :after_add,
    :after_remove => :after_remove

  def after_add client
    client.activate if active?
  end

  def after_remove client
    client.gently_deactivate
  end

  def broadcast_to_clients message
    message_hash = JSON.parse message.to_json(only: [:title, :content, :send_at_date, :send_at_time])
    self.clients.each do |client|
      m = client.messages.new message_hash
      m.sender = self
      m.save
    end
  end

  scope :active, where(state: "active")
  scope :inactive, where(state: "inactive")

  state_machine :state, :initial => :active do
    after_transition :on => :activate do |group, transition|
      group.clients.inactive.each {|c| c.activate}
    end

    after_transition :on => :deactivate do |group, transition|
      group.clients.active.each { |client| client.gently_deactivate }
    end

    event :activate do
      transition :inactive => :active
    end

    event :deactivate do
      transition :active => :inactive
    end
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_filter :authenticate_coach!

  def index
    @active_groups = current_coach.groups.active
    @inactive_groups = current_coach.groups.inactive
  end

  def show
    @group = current_coach.groups.find(params[:id])
    @scheduled_messages = @group.
      messages.
      where("send_at > ?", Time.zone.now).
      order("send_at").
      page(params[:page])
    @sent_messages = @group.
      messages.
      where("send_at <= ?", Time.zone.now).
      order("send_at DESC").
      page(params[:page])
  end

  def info
    @group = current_coach.groups.find(params[:id])
  end

  def new
    @group = current_coach.groups.new
  end

  def edit
    @group = current_coach.groups.find(params[:id])
  end

  def create
    @group = current_coach.groups.new(params[:group])

    if @group.save
      redirect_to @group, notice: 'Group was successfully created.'
    else
      render "new"
    end
  end

  def update
    @group = current_coach.groups.find(params[:id])

    if @group.update_attributes(params[:group])
      redirect_to @group, notice: 'Group was successfully updated.'
    else
      render "edit"
    end
  end

  def destroy
    @group = current_coach.groups.find(params[:id])
    @group.destroy
    redirect_to coach_groups_path(current_coach)
  end

  def active
    @group = current_coach.groups.find(params[:id])
    @group.activate
    redirect_to :back, notice: 'Group was successfully activated.'
  end

  def deactive
    @group = current_coach.groups.find(params[:id])
    @group.deactivate
    redirect_to :back, notice: 'Group was successfully deactivated.'
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
  def format_message_detail message
    if message.title.present?
      title = "<strong>" + message.title + "</strong><hr />"
    else
      title = ""
    end
    content = message.content.gsub(/\n/, '<br/>') if message.content.present?
    [title, content].join(' ').html_safe
  end

  def format_message_info message
    "Email from #{message.sender.name} at #{time_ago_in_words message.created_at} ago"
  end
end

app/views/groups/_form.html.erb
<%= f.error_notification %>
<%= f.input :state, :as => :hidden, :input_html => { :value => params[:state] } if params[:state].present? %>
<% group.errors.each do |a| %>
  <%= a %>
<% end %>

<div class="form-inputs">
  <%= f.input :name, required: true, label: "Name of Group" %>

  <%= f.association :clients,
    :label => "Add Existing Client",
    :input_html => { :class => 'chzn-select', "data-placeholder" => "Click here to add" },
    :collection => current_coach.clients.all %>

  <%= f.input :note, input_html: { cols: 8, rows: 5 }, label: t(:Coach) + " notes", placeholder: "Write notes here..." %>
</div>

<div class="form-actions">
  <%= f.button :submit, 'Save', class: "btn btn-primary" %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                coach_groups_path(current_coach), :class => 'btn' %>
</div>

app/views/groups/_groups_table.html.erb
<table class="table table-bordered table-stripped">
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% groups.each do |group| %>
      <tr>
        <td>
          <%= link_to group.name, group %>
        </td>
        <td>
          <%= link_to "New Message", new_group_message_path(group), data: { target: "#myModal", toggle: "modal" }, class: "btn pull-right" %>
        </td>
        <td>
          <% if group.inactive? %>
            <%= link_to active_group_path(group), :method => :put, class: "btn" do %>
              <i class="icon-arrow-up"></i>
            <% end %>
          <% else %>
            <%= link_to deactive_group_path(group), :method => :put, class: "btn" do %>
              <i class="icon-arrow-down"></i>
            <% end %>
          <% end %>
        <td>
          <%= link_to group_path(group), :method => :delete, :confirm => "Are you sure you would like to delete this group from the database?" do %>
            <i class="icon-trash"></i>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/groups/edit.html.erb
<%= render 'coaches/nav' %>
  <span class="nav nav-back">
    <%= link_to raw("&laquo") + " Back to Groups Dashboard", coach_groups_path(current_coach) %>
  </span>
<section>

  <h1>Edit group</h1>

  <%= simple_form_for @group do |f| %>
    <%= render 'form', group: @group, f: f %>
  <% end %>
</section>

app/views/groups/index.html.erb
<%= render 'coaches/nav' %>
<section>

  <h1>Groups Dashboard
    <div class="pull-right">
      <%= link_to raw('<i class="icon-envelope"></i> New Message'), new_message_path, data: { target: "#myModal", toggle: "modal" }, class: "btn" %>
      <%= link_to raw('<i class="icon-plus"></i> New Group'), new_coach_group_path(current_coach, state:"active"), class: "btn" %>
      
    </div>
  </h1>
  <hr />

  <h2>Active Groups</h2>
  <%= render 'groups_table', coach: current_coach, groups: @active_groups %>

  <h2>Inactive Groups</h2>
  <%= render 'groups_table', coach: current_coach, groups: @inactive_groups %>

</section>

app/views/groups/info.html.erb
<%= render 'coaches/nav' %>
<span class="nav nav-back">
  <%= link_to raw("&laquo") + " Back to Groups Dashboard", coach_groups_path(current_coach) %>
</span>
<section>

  <div class="row-fluid">
    <div class="span6">
      <h1>
        <%= @group.name %>
      </h1>

      <h3>Group Information</h3>
      <p>
        <strong>Name of Group:</strong>
        <%= @group.name %>
      </p>

      <p>
        <strong>Clients:</strong>
        <ul>
          <% @group.clients.each do |client| %>
            <li>
              <%= link_to client.name, client %>
            </li>
          <% end %>
        </ul>
      </p>

      <% if @group.note.present? %>
        <p>
          <strong><%= t(:Coach) %> Private Notes:</strong>
          <%= @group.note %>
        </p>
      <% end %>

      <%= link_to "Back", group_path(@group), class: "btn" %>
      <%= link_to 'Edit', edit_group_path(@group), class: "btn btn-primary" %>
    </div>
  </div>
</section>

app/views/groups/new.html.erb
<%= render 'coaches/nav' %>

<span class="nav nav-back">
  <%= link_to raw("&laquo") + " Back to Groups Dashboard", coach_groups_path(current_coach) %>
</span>

<section>

  <h1>New group</h1>

  <%= simple_form_for [current_coach, @group] do |f| %>
    <%= render 'form', group: @group, f: f %>
  <% end %>
</section>

app/views/groups/show.html.erb
<%= render 'coaches/nav' %>

<span class="nav nav-back">
  <%= link_to raw("&laquo") + " Back to Groups Dashboard", coach_groups_path(current_coach) %>
</span>

<section>
  <h1>
    <%= @group.name %>
    <%= link_to info_group_path(@group) do %>
      <i class="icon-info-sign"></i>
    <% end %>
  </h1>

  <ul class="nav nav-tabs">
    <li class="active">
      <a data-toggle="tab" href="#message_board">Message Board&nbsp;&nbsp;<span class="badge"><%= @sent_messages.count %></span></a>
    </li>
    <li>
      <a data-toggle="tab" href="#scheduled_messages">Scheduled Messages&nbsp;&nbsp;<span class="badge"><%= @scheduled_messages.count %></span></a>
    </li>
  </ul>
  <%= link_to "New Message", new_group_message_path(@group), data: { target: "#myModal", toggle: "modal" }, class: "btn pull-right" %>
  <div class="tab-content">
    <div class="tab-pane active" id="message_board">
      <% @sent_messages.each do |message| %>
        <% if message.receiver.is_a?(Group) %>
          <p>
            <%= format_message_detail(message) %>
          </p>
          <small>
            <%= format_message_info(message) %>
          </small>
          <p>
            <%= link_to message, method: :delete, confirm: "Sure?" do %>
              <i class="icon-remove pull-right"></i>
            <% end %>
          </p>
        <% end %>
      <% end %>
    </div>
    <div class="tab-pane" id="scheduled_messages">
      <%= render 'messages/scheduled_messages', coach: current_coach, group: @group, messages: @scheduled_messages if @scheduled_messages.any? %>
    </div>
  </div>
</section>