config/routes.rb
FitnessManager::Application.routes.draw do

  devise_for :coaches, controllers: {
    registrations: 'coaches/registrations'
  }
  devise_for :clients, controllers: {
    registrations: 'clients/registrations'
  }

  resources :coach_steps

  resources :messages do
    collection do
      post :inbound
      get :inbound
    end
    member do
      post :confirm
      get :reply
    end
  end

  resources :coaches, shallow: true do

    collection do
      get :settings
      get :edit_profile
      put :update_profile
    end

    resources :messages do
      collection do
        post :inbound
        get :inbound
        get :scheduled
      end
      member do
        post :confirm
      end
    end

    resources :clients do
      collection do
        get :checkins
      end
      resources :messages
      member do
        get :info
        get :goals
        get :dashboard
        put :active
        put :deactive
      end
      resources :habits do
        member do
          put :active
          put :deactive
        end
      end
      resources :goals do
        member do
          put :active
          put :deactive
        end
      end
    end

    resources :groups do
      resources :messages
      member do
        get :info
        put :active
        put :deactive
      end
    end
  end

  root :to => "pages#index"
  match '/about' => 'pages#about'
  match '/tips' => 'pages#tips'
  
end

app/models/client.rb
class Client < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable

  attr_accessible :group_id,
    :email,
    :password,
    :password_confirmation,
    :remember_me,
    :first_name,
    :note,
    :phone_number,
    :surname,
    :group_ids,
    :state,
    :client_id,
    :coach_id,
    :checkins_attributes,
    :habits_attributes,
    :dob

  validates_format_of :phone_number,
    :message => "telephone number must containes only digits and plus sign.",
    :with => /^[+0-9]+$/,
    :if => :active?

  belongs_to :coach

  validates :email, :phone_number, :coach, :first_name, :surname,
    presence: true

  validates_uniqueness_of :email

  validates :phone_number, :length => { :maximum => 15}

  has_and_belongs_to_many :groups,
    :after_add => Proc.new { |client, group| client.activate if group.active? },
    :after_remove => Proc.new { |client, group| client.gently_deactivate }

  has_many :sent_messages, as: :sender, class_name: "Message", dependent: :destroy
  has_many :messages, as: :receiver, class_name: "Message", dependent: :destroy

  has_many :habits, dependent: :destroy
  accepts_nested_attributes_for :habits, allow_destroy: true
  has_many :goals, dependent: :destroy

  has_many :checkins, through: :habits
  accepts_nested_attributes_for :checkins

  def coach_replied_last?
    msg = self.messages.last
    msg.present? && msg.coach_id.present?
  end

  def gently_deactivate
    deactivate unless enrolled_in_any_active_group?
  end

  scope :active, where(state: "active")
  scope :inactive, where(state: "inactive")

  def today_checkins
    # check each a
    self.habits.active.each do |habit|
      habit.checkins.today.first_or_create(
        checked: false,
        client_id: self.id
      )
    end
    self.checkins.joins(:habit).where("habits.state ='active'").today
  end

  def latest_checkins
    self.checkins.where(checked: true).order("updated_at DESC").limit(3)
  end

  def enrolled_in_any_active_group?
    groups.where(state: "active").exists?
  end

  state_machine :state, :initial => :inactive do
    event :activate do
      transition all => :active
    end

    event :deactivate do
      transition all => :inactive
    end
  end

  def dob_with_format
    if self.dob.year == 1970
      "#{self.dob.day}/#{self.dob.month}"
    else
      "#{self.dob.day}/#{self.dob.month}/#{self.dob.year}"
    end
  end

  def name
    "#{first_name} #{surname}"
  end

  def dob=(dob)
    if dob.instance_of?(String) && dob.match(/\d+\/\d+\/\d+/)
      day, month, year = dob.split('/').map { |date| date.to_i }
      if year + 2000 > Date.today.year
        year += 1900
      else
        year += 2000
      end

      dob = Date.new(year, month, day)
    end
    write_attribute(:dob, dob)
  end

  def coach_unreplied_messages_count
    last_coach_message = messages.last
    if last_coach_message.present?
      sent_messages.where("send_at > ?", last_coach_message.send_at).where(state: :confirmed).count
    else
      0
    end
  end

  def client_unreplied_messages_count
    last_client_message = sent_messages.last
    if last_client_message.present?
      messages.where("send_at > ?", last_client_message.send_at).where(state: :confirmed).count
    else
      0
    end
  end

  def related_messages
    Message.where("(sender_type = 'Client' AND sender_id = ?) OR (receiver_type = 'Client' AND receiver_id = ?)", id, id)
  end

  def past_messages
    self.related_messages.
      where("send_at <= ?", Time.zone.now).
      where(state: "confirmed").
      order("created_at DESC")
      
      #page(params[:page])
  end

  def messaged_last?
    if self.messages.any? && self.sent_messages.any?
      self.sent_messages.last.send_at > self.messages.last.send_at
    elsif self.sent_messages.any? && self.messages.empty?
      true
    else
      false
    end
  end

  def to_param
    "#{id}-#{first_name.downcase}-#{surname.downcase}"
  end
end

app/controllers/clients/registrations_controller.rb
class Clients::RegistrationsController < Devise::RegistrationsController
  def create
    build_resource
    client = Client.find_by_email resource.email

    if client.present? && client.encrypted_password.blank?
      client.update_attributes(
        password: resource.password,
        password_confirmation: resource.password_confirmation,
        first_name: resource.first_name,
        surname: resource.surname,
        phone_number: resource.phone_number,
      )
      set_flash_message :notice, :signed_up if is_navigational_format?
      sign_in(resource_name, client)
      respond_with client, :location => after_sign_in_path_for(client)
    elsif resource.save
      if resource.active_for_authentication?
        set_flash_message :notice, :signed_up if is_navigational_format?
        sign_up(resource_name, resource)
        respond_with resource, :location => after_sign_up_path_for(resource)
      else
        set_flash_message :notice, :"signed_up_but_#{resource.inactive_message}" if is_navigational_format?
        expire_session_data_after_sign_in!
        respond_with resource, :location => after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      respond_with resource
    end
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_filter :authenticate_coach!, only: [:show]
  before_filter do
    if current_coach != nil
     authenticate_coach!
    else
     authenticate_client!
    end
  end

  before_filter :find_client, only: [:edit, :info, :goals, :show, :update]
  helper_method :sort_column, :sort_direction

  def index
    @active_clients = current_coach.clients.active.
      order(sort_column + " " + sort_direction)
    @inactive_clients = current_coach.clients.inactive.
      order(sort_column + " " + sort_direction)
  end

  def dashboard
    @client = current_client
    @messages = @client.related_messages.
      where("send_at <= ?", Time.zone.now).
      where(state: "confirmed").
      order("created_at DESC").
      page(params[:page])
    @unreplied_messages_count = @client.client_unreplied_messages_count
    @today_checkins = @client.today_checkins
    @latest_checkins = @client.latest_checkins
    @active_goal = @client.goals.active.first
  end

  def checkins
    @checkins = current_coach.checkins.limit(50)
  end

  def info
  end

  def goals
    @habits = @client.habits.order("id DESC")
    @inactive_habits = @client.habits.inactive
    @active_habits = @client.habits.active
    @inactive_goals = @client.goals.inactive
    @active_goal = @client.goals.active.last
    @today_checkins = @client.today_checkins
    @latest_checkins = @client.checkins.where(checked: true).order("updated_at DESC").limit(3)
  end

  def show
    @messages = @client.related_messages.
      where("send_at <= ?", Time.zone.now).
      where(state: "confirmed").
      order("created_at DESC").
      page(params[:page])
    @scheduled_messages = @client.
      messages.
      where("send_at > ?", Time.zone.now).
      order("created_at DESC").
      page(params[:page])
    @today_checkins = @client.today_checkins
    @latest_checkins = @client.checkins.where(checked: true).order("updated_at DESC").limit(3)
    @unreplied_messages_count = @client.coach_unreplied_messages_count
    @active_goal = @client.goals.active.first
  end

  def new
    @client = current_coach.clients.new
  end

  def edit
  end

  def create
    @client = current_coach.clients.new(params[:client])

    if @client.save
      if mobile?
        redirect_to :back, notice: 'Client was successfully created.'
      else
        redirect_to @client, notice: 'Client was successfully created.'
      end
    else
      render "new"
    end
  end

  def update
    if @client.update_attributes(params[:client])
      if coach_signed_in?
        if params[:client][:checkins_attributes].present?
          redirect_to goals_client_path(@client)
        else
          redirect_to info_client_path(@client)
        end
      else
        respond_to do |f|
          f.html { redirect_to dashboard_client_path(@client) }
          f.json {
            render :json => {
              :status => :ok,
              :message => "Success!",
              :html => ""
            }.to_json
          }
        end
      end
    else
      render "edit"
    end
  end

  def destroy
    @client = current_coach.clients.find(params[:id])
    @client.destroy

    redirect_to coach_clients_path(current_coach)
  end

  def active
    @client = current_coach.clients.find(params[:id])
    @client.activate
    redirect_to :back, notice: 'Client was successfully activated.'
  end

  def deactive
    @client = current_coach.clients.find(params[:id])
    @client.deactivate
    redirect_to :back, notice: 'Client was successfully deactivated.'
  end

  private

  def find_client
    if coach_signed_in?
      @client = current_coach.clients.find(params[:id])
    elsif client_signed_in?
      @client = current_client
    else
      redirect_to root_path
    end
  end

  def sort_column
    params[:sort] || "first_name"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

end

app/helpers/clients_helper.rb
module ClientsHelper
  def format_message_detail message
    if message.title.present?
      title = "<strong>" + message.title + "</strong><br />"
    else
      title = ""
    end
    content = message.content.gsub(/\n/, '<br/>') if message.content.present?
    [title, content].join(' ').html_safe
  end

  def format_message_info message
    "Email from #{message.sender.name} at #{time_ago_in_words message.send_at} ago"
  end

  def format_checkin_time client
    time_ago_in_words(client.checkins.where(checked: true).last.updated_at) + ' ago' if client.checkins.where(checked: true).any?
  end

  def checkins_chart_data client
    (4.weeks.ago.to_date..Date.today).map do |date|
      {
        checkin_at: date,
        checkin_count: client.checkins.where(checked: true).where("date(checkins.updated_at) = ?", date).count
      }
    end
  end

  def link_to_add_fields name, f, association
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize + "_fields", f: builder)
    end
    link_to(name, '#', class: "add_fields", data: {id: id, fields: fields.gsub("\n", "")})
  end

  def fancy_birthday(bir)
    day = bir.change(year: Date.today.year)
    fancyday = day - Date.today

    if fancyday < 0
      day = bir.change(year: Date.today.year+1)
      fancyday = day - Date.today
    end
    "in #{fancyday.to_i} days time"
  end

  def sortable(column, title = nil)
    title ||= column.titleize
    css_class = column == sort_column ? "current_#{sort_direction}" : nil
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    chevron_direction = direction == "desc" ? "up" : "down"
    link_to %Q{#{title}<i class="icon-chevron-#{chevron_direction}"></i>}.html_safe, {:sort => column, :direction => direction}, :class => css_class
  end
end

app/views/clients/_active_goal.html.erb
<h3>Long Term Goal</h3>
<div class="alert alert-info">
  <%= link_to raw('<i class="icon-cog"> </i>'), edit_goal_path(goal), data: { target: "#myModal", toggle: "modal" }, :class => "btn btn-link pull-right" %>
  <h4><%= goal.title %> <small><%= deadline_nice @active_goal %></small></h4>
  <p><%= goal.description %></p>
</div>

app/views/clients/_checkable_active_habits.html.erb
<div id="checkin_box">
  <%= simple_form_for client do |f| %>
    <table class="table table-bordered table-stripped">
      <thead>
        <tr>
          <th></th>
          <th>Habit</th>
          <th>Check-in</th>
          <th>De/Activate</th>
          <th>Trash</th>
        </tr>
      </thead>
      <tbody>
        <% counter = 1 %>
        <%= f.simple_fields_for :checkins, today_checkins do |ff| %>
          <tr id="checkin-<%= ff.object.id %>">
            <td>
              <%= counter %>
              <% counter += 1 %>
            </td>
            <td>
              <%= link_to ff.object.habit.title, edit_habit_path(ff.object.habit), data: { target: "#myModal", toggle: "modal" } %>
            </td>
            <td>
              <%= ff.input :checked,
                label: false,
                input_html: { title: "Simply checkin and track your progress" }
              %>
            </td>
            <td>
              <% if ff.object.habit.active? %>
                <%= link_to deactive_habit_path(ff.object.habit), :method => :put, class: "btn" do %>
                  <i class="icon-arrow-down"></i>
                <% end %>
              <% else %>
                <%= link_to active_habit_path(ff.object.habit), :method => :put, class: "btn" do %>
                  <i class="icon-arrow-up"></i>
                <% end %>
              <% end %>
            </td>
            <td>
              <%= link_to ff.object.habit, :method => :delete, :confirm => "Are you sure you would like to delete this habit from the database?" do %>
              <i class="icon-remove"></i>
            <% end %>
          </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end if today_checkins.exists? %>
</div>

app/views/clients/_client_head.html.erb
<%= render :partial => 'clients/client_head_name' %>

<ul class="nav nav-tabs">
  <li <% if clienthead == "messages" || clienthead.blank? %>class="active"<% end %>>
    <%= link_to "Messages", client_path(@client) %>
  </li>
  <li <% if clienthead == "goals" %>class="active"<% end %>>
    <%= link_to "Goals & Habits", client_goals_path(@client) %>
  </li>

  <% if coach_signed_in? %>
    <li <% if clienthead == "info" %>class="active"<% end %>>
      <%= link_to info_client_path(@client) do %>
        Client Info
      <% end %>
    </li>
  <% end %>

</ul>

app/views/clients/_client_head_name.html.erb
<h1>
  <%= @client.name %>
  <% if @active_goal.present? %>
    <small>
      <%= @client.first_name %>'s goal is to:
      <%= link_to @active_goal.title || @active_goal.content, client_goals_path(@client) %>
      <%= deadline_nice @active_goal %>
    </small>
  <% end %>

  <% if coach_signed_in? %>
    <%= link_to new_client_message_path(@client), data: { target: "#myModal", toggle: "modal" }, class: "btn pull-right" do %>
      <i class="icon-envelope"></i> Message <%= @client.first_name %>
    <% end %>
  <% end %>
</h1>

app/views/clients/_clients_table.html.erb
<ul class="client-table">
  <% clients.each do |client| %>
    <li class="show-child-on-hover">
      <%= link_to [client.first_name, client.surname].join(' '), client, :class => "pull-left" %>

      <div class="pull-left child-for-hover" style="padding-left:10px;">
        <%#= truncate(client.messages.last.content, :length => 50) if client.messages.any? %>
        
        <%= link_to new_client_message_path(client), data: { target: "#myModal", toggle: "modal" }, :class => "icon tooltip-handler", :title => "Message" do %>
          <i class="icon-envelope"> </i>
        <% end %>

        <% if client.persisted? && client.inactive? %>
          <%= link_to active_client_path(client), :method => :put, :class => "icon tooltip-handler", :title => "Activate" do %>
            <i class="icon-arrow-up"> </i>
          <% end %>
        <% elsif client.persisted? && client.active? %>
          <%= link_to deactive_client_path(client), :method => :put, :class => "icon tooltip-handler", :title => "Deactivate" do %>
            <i class="icon-arrow-down"> </i>
          <% end %>
        <% end %>

        <% if !client.active? %>
          <%= link_to client, data: { confirm: "Are you sure you want to permanently delete this client from the database?" }, method: :delete, :class => "icon tooltip-handler", :title => "Delete" do %>
            <i class="icon-remove"> </i>
          <% end %>
        <% end %>
      </div>
    </li>
  <% end %>
</ul>

app/views/clients/_current_goal.html.erb
<% if client.goals.active.any? %>
  <h3>
    <%= link_to "Goal", client_goals_path(client) %>
  </h3>
  <p class="text-info">
    <%= client.first_name %>'s goal is to:
  </p>
  <h5>
    <%= client.goals.active.first.title %>
  </h5>
  <h5>
    <%= deadline_nice @active_goal %>
  </h5>
<% end %>

app/views/clients/_latest_checkins.html.erb
<% if checkins.any? %>
  <div class="check_ins">
    <h3>Last 3 Check Ins:</h3>
    <ul>
      <% checkins.each do |checkin| %>
        <li>
          <%= "Checked in to " %>
          <%= checkin.habit.title %>
          <%= time_ago_in_words checkin.created_at %>
          <%= "ago" %>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/clients/_nav.html.erb
<ul class="nav nav-pills" id="nav-top">
  <li>
    <%= link_to image_tag("logo.png"), root_path, class: "logo" %>
  </li>
  <li>
    <%= link_to "Dashboard", dashboard_client_path(current_client) %>
  </li>
  <li>
    <%= link_to "Goals & Habits", goals_client_path(current_client) %>
  </li>
  <li class="pull-right">
    <%= link_to "Signout", destroy_client_session_path, method: :delete %>
  </li>
  <li class="pull-right">
    <%= link_to "Settings", edit_client_registration_path %>
  </li>
</ul>
<%= bootstrap_flash %>

app/views/clients/_new_client_and_new_message.html.erb
<%= link_to 'New inactive client', new_coach_client_path(coach, state:"inactive"), class: "btn btn-warning #{'pull-right' if local_assigns[:right]}" %>
<%= link_to "New Message", new_message_path, data: { target: "#myModal", toggle: "modal" }, class: "btn btn-warning #{'pull-right' if local_assigns[:right]}" %>

app/views/clients/dashboard.html.erb
<%= render "nav" %>
<section>
  <div class="page-header">
    <%= render :partial => 'clients/client_head_name', :locals => {:client => current_client} %>
  </div>

  <div class="row-fluid">
    <div class="span7">
      <h3>
        <%= link_to new_coach_message_path(current_client.coach), data: { target: "#myModal", toggle: "modal" }, class: "btn pull-right" do %>
          New Message to <%= t(:Coach) %> <i class="icon-envelope"></i>
        <% end %>
        Message Board <span class="badge badge-info"><%= @unreplied_messages_count %></span>
      </h3>

      <div class="tab-content">
        <div class="tab-pane active" id="msg_board">
          <%= render @messages if @messages.any? %>
          <%= paginate @messages %>
        </div>
      </div>
   </div>

    <div class="span4 offset1">
      <h3>
        <%= link_to goals_client_path(@client), class: "btn pull-right" do %>
          Manage Goals <i class="icon-cog"></i>
        <% end %>
      </h3>
      <%= render 'active_goal', client: @client, goal: @active_goal if @active_goal.present? %>

      <h3>
        <%= link_to goals_client_path(@client), class: "btn pull-right" do %>
          Manage Habits <i class="icon-cog"></i>
        <% end %>
        Checkins for Today
      </h3>
      <%= render 'clients/checkable_active_habits', client: @client, today_checkins: @today_checkins %>
      
      <%= render 'clients/latest_checkins', checkins: @latest_checkins %>
     
      <h3>
        Checkin History
      </h3>
      <%= render 'habits/habits_chart', client: @client %>
      
    </div>
  </div>
</section>

app/views/clients/goals.html.erb
<% if coach_signed_in? %>
  <%= render 'coaches/nav' %>
  <span class="nav nav-back">
    <%= link_to raw("&laquo") + " Back to Clients Dashboard", coach_clients_path(current_coach) %>
  </span>
<% else %>
  <%= render 'clients/nav' %>
<% end %>

<section>
  <div class="row-fluid">
    <div class="span12">
      <% if coach_signed_in? %>
        <%= render :partial => 'clients/client_head', :locals => { :clienthead => "goals" }  %>
      <% end %>

      <h2>
        <%= link_to raw('<i class="icon-plus"></i> New goal'), new_client_goal_path(@client), data: { target: "#myModal", toggle: "modal" }, class: "btn pull-right" %>
        Goals
      </h2>

      <%= render 'active_goal', client: @client, goal: @active_goal if @active_goal.present? %>
      <%= render 'inactive_goals', client: @client, goals: @inactive_goals if @inactive_goals.any? %>
      
      <hr />
      <h2>
        <%= link_to raw('<i class="icon-plus"></i> New Habit'), new_client_habit_path(@client), data: { target: "#myModal", toggle: "modal" }, class: "btn pull-right" %>
        Habits
      </h2>
      <%= render 'clients/checkable_active_habits', client: @client, today_checkins: @today_checkins %>
      <% if @inactive_habits.any? %>
        <h3>Inactive Habits</h3>
        <%= render 'habits/habits_table', client: @client, habits: @inactive_habits %>
      <% end %>
      <h3>
        Checkin Timeline
      </h3>
      <%= render 'habits/habits_chart', client: @client %>
      <%= render 'clients/latest_checkins', checkins: @latest_checkins %>


    </div>
  </div>
</section>

app/views/clients/index.html.erb
<%= render :partial => 'coaches/nav' %>
<section>
  <div class="row-fluid">
    <div class="span12">
      <h1>
        <div class="pull-right">
          <%= link_to raw('<i class="icon-plus"></i> New Client'), new_coach_client_path(current_coach, state:"active"), class: "btn" %>
          <%= link_to raw('<i class="icon-plus"></i> New Message'), new_message_path, data: { target: "#myModal", toggle: "modal" }, class: "btn " %>
        </div>
        Clients Dashboard
      </h1>
      <hr />
      <h2>
        Active Clients
      </h2>
      <hr />
      <%= render 'clients_table', clients: @active_clients %>
      <% if !@active_clients.any? %>
        <em>No active clients</em>
      <% end %>
    </div>
  </div>
  <% if @inactive_clients.any? %>
    <hr />
    <div class="row-fluid">
      <div class="span12">
        <h2>Inactive Clients</h2>
        <hr />
        <%= render 'clients_table', clients: @inactive_clients %>
      </div>
    </div>
  <% end %>
</section>

app/views/clients/info.html.erb
<% if coach_signed_in? %>
  <%= render 'coaches/nav' %>
  <span class="nav nav-back">
    <%= link_to raw("&laquo") + " Back to Clients Dashboard", coach_clients_path(current_coach) %>
  </span>
<% else %>
  <%= render 'clients/nav' %>
<% end %>

<section>
  <div class="row-fluid">
    <div class="span12">

      <%= render :partial => 'clients/client_head', :locals => { :clienthead => "info" }  %>

      <h2>
        <% if coach_signed_in? %>
          <div>
            <%= link_to raw('<i class="icon-cog"></i> Edit Client'), edit_client_path(@client), class: "btn pull-right" %>
          </div>
        <% end %>
        <%= @client.name %>'s Account Settings
      </h2>

      <dl class="dl-horizontal">

        <dt><strong>First name:</strong></dt>
        <dd><%= @client.first_name %></dd>

        <dt><strong>Surname:</strong></dt>
        <dd><%= @client.surname %></dd>

        <dt><strong>Phone number:</strong></dt>
        <dd><%= @client.phone_number %></dd>

        <dt><strong>Email:</strong></dt>
        <dd><%= mail_to @client.email, @client.email, subject: @client.coach.brand_name %></dd>

        <% if @client.dob.present? %>
          <dt><strong>Date of Birth:</strong></dt>
          <dd> <%= @client.dob_with_format %> <%= fancy_birthday(@client.dob) %></dd>
        <% end %>

        <dt><strong><%= t(:Coach) %>:</strong></dt>
        <dd><%= @client.coach.name %></dd>

        <dt><strong>Current Groups:</strong></dt>
        <dd>
          <ul>
            <% @client.groups.each do |group| %>
              <li>
                <%= link_to group.name, group %>
              </li>
            <% end %>
          </ul>
        </dd>

      <% if coach_signed_in? %>
        <dt><strong><%= t(:Coach) %> Private Notes:</strong></dt>
        <dd><%= @client.note %></dd>
      <% end %>

    </div>
  </div>
</section>

app/views/clients/show.html.erb
<%= render 'coaches/nav' %>

<span class="nav nav-back">
  <%= link_to raw("&laquo") + " Back to Clients Dashboard", coach_clients_path(current_coach) %>
</span>

<section>
  <div class="row-fluid">
    <div class="span12">

      <%= render :partial => 'clients/client_head', :locals => { :clienthead => "messages" } %>

      <h3>
        Message Board <span class="badge badge-info"><%= @unreplied_messages_count %></span>
      </h3>
      <%= render @messages if @messages.any? %>
      <%= paginate @messages %>

      <% if coach_signed_in? %>
        <hr />
        <h3>
          Scheduled Messages <span class="badge badge-info"><%= @scheduled_messages.count %></span>
        </h3>
          <%= render 'messages/scheduled_messages', coach: current_coach, client: @client, messages: @scheduled_messages if @scheduled_messages.any? %>
      <% end %>

    </div>
  </div>
</section>